spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion_de_reclamation?useTimezone=true&serverTimezone=UTC
    username: root
    password: imane123456789
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  